language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script: mvn test
before_install:
 - chmod +x after_success.sh
after_success:
- mvn clean deploy:deploy -q --settings settings.xml
